### ISSUE TITLE
Счётчик публикаций и комментариев сломался

### ISSUE THREAD

**Issue by zclimber** [Suvitruf/dtf-scripts#6]
Вызов GET | https://api.dtf.ru/v1.9/user/83166 возвращает код 403 и уточнение "Тело ответа недоступно для сценариев (Причина: CORS Missing Allow Origin)" от Firefox

**Comment by Suvitruf** [comment]
Такая проблема с юзерами, которые либо сами сделали профиль не публичным, либо если его модераторы скрыли. С этим ничего не поделать )=
